version: "3.7"

services:
  postgres:
    image: postgres
    container_name: nf-shard-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    profiles:
      - db
      - all

  nextjs:
    image: ghcr.io/gallvp/nf-shard:latest
    container_name: nf-shard-nextjs
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - ./docker/entrypoint.sh:/app/entrypoint.sh
    platform: linux/amd64
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
    ports:
      - 3000:3000
    profiles:
      - server
      - all
    depends_on:
      - postgres

volumes:
  postgres-data:
