name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: actions/setup-node@v4.4.0
      
      - run: yarn
    
      - name: Start PostgreSQL DB
        run: docker compose --profile db up --detach
      
      - name: Run the tests
        run: yarn test:cypress:all
